export const FETCH_PUBLIC_PRODUCTS_START = 'FETCH_PUBLIC_PRODUCTS_START';
export const FETCH_PUBLIC_PRODUCTS_SUCCESS = 'FETCH_PUBLIC_PRODUCTS_SUCCESS';
export const FETCH_PUBLIC_PRODUCTS_FAILURE = 'FETCH_PUBLIC_PRODUCTS_FAILURE';